### ISSUE TITLE
CSV tests

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/converter#5]
Here is a lib to consider using for testing CSV parsing: https://github.com/maxogden/csv-spectrum

**Comment by doowb** [comment]
Good idea. This might be something useful to do with other types of tests in other repos... eg extract all the test files to a requirable repo.

**Comment by jonschlinkert** [comment]
> this might be something useful to do with other types of tests in other repos.

awesome, let's do that. I think I started doing this a while back for templates and data, and it might be published somewhere already. If not we can use node-foo. A bogus module I published on npm for testing purposes. 

actually... hmmm. What if we grabbed the test fixtures (credited of course) from several of the libs we use for yaml, json, templates, etc. and just put them up in this test repo? this seems like a great way to keep that junk out of some of our projects

**Comment by doowb** [comment]
I was looking into using csv-spectrum for tests since I wanted to get this project finished up and ready to use in grunt-convert and gulp-convert, but I'm running into an issue with [node-csv](https://github.com/wdavidw/node-csv).

It seems that it behaves differently based on the type of output (eg, to a file, a stream, or string). It might be good to find another library for this.

**Comment by jonschlinkert** [comment]
closing these since I already created a csv parsing lib
